export const footerLinks = {
    quickLinks: [
      { text: "Downloads", link: "https://access.redhat.com/downloads/" },
      { text: "Subscriptions", link: "https://access.redhat.com/downloads/" },
      { text: "Support Cases", link: "https://access.redhat.com/support" },
      { text: "Customer Service", link: "https://access.redhat.com/support/customer-service" },
      { text: "Product Documentation", link: "https://access.redhat.com/downloads/" },
    ],
    helpLinks: [
      { text: "Contact Us", link: "https://access.redhat.com/support/contact/" },
      { text: "Customer Portal FAQ", link: "https://access.redhat.com/articles/33844" },
      { text: "Log-in Assistance", link: "https://access.redhat.com/help/login_assistance" },
    ],
    siteInfoLinks: [
      { text: "Trust Red Hat", link: "https://www.redhat.com/en/trust" },
      { text: "Browser Support Policy", link: "https://www.redhat.com/en/about/browser-support" },
      { text: "Accessibility", link: "https://www.redhat.com/en/about/digital-accessibility" },
      { text: "Awards and Recognition", link: "https://access.redhat.com/recognition/" },
      { text: "Colophon", link: "https://access.redhat.com/help/colophon/" },
    ],
    relatedSiteLinks: [
      { text: "redhat.com", link: "https://www.redhat.com/en" },
      { text: "developers.redhat.com", link: "https://developers.redhat.com/" },
      { text: "connect.redhat.com", link: "https://connect.redhat.com/en" },
      { text: "cloud.redhat.com", link: "https://cloud.redhat.com/" },
    ],
    aboutLinks: [
      { text: "Red Hat Subscription Value", link: "https://access.redhat.com/subscription-value" },
      { text: "About Red Hat", link: "https://www.redhat.com/en/about?sc_cid=701600000011iJjAAI" },
      { text: "Red Hat Jobs", link: "https://www.redhat.com/en/jobs" },
    ],
    infoLinks: [
      { text: "About Red Hat", link: "https://www.redhat.com/en/jobs" },
      { text: "Jobs", link: "https://www.redhat.com/en/jobs" },
      { text: "Events", link: "https://www.redhat.com/en/jobs" },
      { text: "Locations", link: "https://www.redhat.com/en/jobs" },
      { text: "Contact Red Hat", link: "https://www.redhat.com/en/jobs" },
      { text: "Red Hat Blog", link: "https://www.redhat.com/en/jobs" },
      { text: "Diversity, equity, and inclusion", link: "https://www.redhat.com/en/jobs" },
      { text: "Cool Stuff Store", link: "https://www.redhat.com/en/jobs" },
      { text: "Red Hat Summit", link: "https://www.redhat.com/en/jobs" },
    ],
    privacyLinks: [
      { text: "Privacy statement", link: "https://www.redhat.com/en/about/privacy-policy" },
      { text: "Terms of use", link: "https://www.redhat.com/en/about/terms-use" },
      { text: "All policies and guidelines", link: "https://www.redhat.com/en/about/all-policies-guidelines" },
      { text: "Digital accessibility", link: "https://www.redhat.com/en/about/digital-accessibility" },
      { text: "Cookie preferences", link: "https://www.redhat.com/en/jobs" },
    ],
  };